apps/book_review/urls.py
from django.conf.urls import url
from . import views

app_name = 'book_review'

urlpatterns = [
    url(r'^$', views.start, name = 'start'),
    url(r'^add$', views.add, name='add'),
    url(r'^add_book$', views.add_book, name='add_book'),
    url(r'^(?P<book_id>[0-9]+$)', views.review_book, name="review_book"),
    url(r'^submit_review/(?P<book_id>[0-9]+$)', views.submit_review, name="submit_review"),
    url(r'^users/(?P<user_id>[0-9]+$)', views.user, name="user"),
]

apps/login_registration/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'login_registration'

urlpatterns = [
    url(r'^$', views.start, name='start'),
    url(r'^actions', views.submit, name='actions'),
]

main/urls.py
from django.conf.urls import url, include
#from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_registration.urls')),
    url(r'^book_review/', include('apps.book_review.urls')),
]

apps/book_review/models.py
from __future__ import unicode_literals
from ..login_registration.models import User
from django.db import models

# Create your models here.

class AuthorManager(models.Manager):

    def check_name(self, name):
        if len(name) < 2:
            return False
        return True

    def check_exists(self, name):
        if Author.objects.filter(name=name).exists():
            return True
        return False

class BookManager(models.Manager):

    def check_name(self, title):
        if len(title) < 2:
            return False
        return True

    def check_exists(self, title):
        if Book.objects.filter(title=title).exists():
            return True
        return False

class ReviewManager(models.Manager):

    def check_review(self, review):
        if len(review) < 2:
            return False
        return True

class Author(models.Model):
    name = models.TextField(max_length=100)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = AuthorManager()

class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.ForeignKey(Author, related_name="books")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = BookManager()

class Review(models.Model):
    review = models.CharField(max_length = 355)
    rating = models.IntegerField()
    user = models.ForeignKey(User, related_name="reviews")
    book = models.ForeignKey(Book, related_name="reviews")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = ReviewManager()

apps/book_review/views.py
from django.shortcuts import render, redirect
from .models import Book, Author, Review
from ..login_registration.models import User

# Create your views here.

def start(request):
    context={
        'reviews': reversed(Review.objects.all().order_by('-id')[:3]),
        'books': Book.objects.all(),
    }
    return render(request, 'book_review/start.html', context)

def add(request):
    context={
        'authors': Author.objects.all(),
    }
    return render(request, 'book_review/add.html', context)

def add_book(request):
    if request.method == 'POST':
        if request.POST['add']=='review':
            #Author
            print request.POST.keys()
            if 'author' in request.POST and request.POST['author']:
                author = request.POST['author']
                author = Author.objects.get(name=author)
            elif request.POST['new_author']:
                author = Author.objects.create(name=request.POST['new_author'])
            new_book = Book.objects.create(title=request.POST['book_title'], author=author)
            #Rating & Review
            user = User.objects.get(id=request.session['user_id'])
            review = Review.objects.create(review=request.POST['review'], rating=request.POST['rating'], user=user, book=new_book)
            return redirect('book_review:review_book', book_id=new_book.id)

def review_book(request, book_id):
    context={
        'book': Book.objects.get(id=book_id),
        'reviews': Review.objects.filter(book=Book.objects.get(id=book_id))
    }
    return render(request, 'book_review/book.html', context)

def submit_review(request, book_id):
    if request.method=='POST':
        user=User.objects.get(id=request.session['user_id'])
        book=Book.objects.get(id=book_id)
        new = Review.objects.create(review=request.POST['review'], rating=request.POST['rating'], user=user, book=book)
        return redirect('book_review:review_book', book_id=book_id)

def user(request, user_id):
    context={
        'user': User.objects.get(id=user_id),
        'reviews': Review.objects.filter(user=User.objects.get(id=user_id)),
        'count': Review.objects.filter(user=User.objects.get(id=user_id)).count(),
    }
    return render(request, 'book_review/user.html', context)

apps/book_review/templates/book_review/add.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Add Book</title>
    </head>
    <body>
        <div class="container">
            <a href="{% url 'book_review:start' %}">Home</a>
            <a href="{% url 'login_registration:start' %}">Logout</a>
            <div class="add">
                <form action="{% url 'book_review:add_book' %}" method="post">
                    {% csrf_token %}
                    <label for="book_title">Book Title</label>
                    <input type="text" name="book_title">
                    <h3>Author:</h3>
                    <label for="author">Choose from the list:</label>
                    <select name="author">
                        <option value=""></option>
                    {% if authors %}
                        {% for author in authors %}
                            <option value="{{author.name}}">{{author.name}}</option>
                        {% endfor %}
                    {% endif %}
                    </select>
                    <label for="new_author">Or add a new author:</label>
                    <input type="text" name="new_author">
                    <label for="review">Review:</label>
                    <textarea rows="4" cols="50" name="review"></textarea>
                    <label for="rating">Rating:</label>
                    <select name="rating">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                    <button type="submit" name="add" value="review">Add Book and Review</button>
                </form>
            </div>
        </div>
    </body>
</html>

apps/book_review/templates/book_review/book.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Book</title>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <a href="{% url 'book_review:start' %}">Home</a>
                <a href="{% url 'login_registration:start' %}">Logout</a>
                <h1>{{book.title}}</h1>
                <label for="author">Author:</label>
                <p name="author">{{book.author.name}}</p>
            </div>
            <div class="reviews">
                {% if reviews %}
                    {% for review in reviews %}
                        <label for="rating">Rating:</label>
                        <p name="rating">{{review.rating}}<p>
                        <p><a href="{% url 'book_review:user' user_id=review.user.id %}">{{review.user.name}}</a> says: {{review.review}}</p>
                        <p>{{review.created_at}}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="new_review">
                <form action="{% url 'book_review:submit_review' book_id=book.id %}" method="post">
                    {% csrf_token %}
                    <textarea rows="4" cols="50" name="review"></textarea>
                    <label for="rating">Rating:</label>
                    <select name="rating">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                    <button type="submit" name="submit" value="submit">Submit Review</button>
                </form>
            </div>
        </div>
    </body>
</html>

apps/book_review/templates/book_review/start.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Front Page</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'login_registration/css/start_style.css' %}">
    </head>
    <style>
    #scroll{
        width: 325px;
        height: 150px;
        line-height:3em;
        overflow: scroll;
        padding:5px;
        border-style: solid;
    }
    </style>
    <body>
        <div class="container">
            <div class="header">
                <p>Welcome, {{request.session.user_name}}!</p>
                <a href="{% url 'book_review:add' %}">Add Book and Review</a>
                <a href="{% url 'login_registration:start' %}">Logout</a>
            </div>
            <div class="reviews">
                <h2>Recent Book Reviews:</h2>
                {% if reviews %}
                    {% for review in reviews %}
                        <a href="{% url 'book_review:review_book' book_id=review.book.id %}">{{review.book.title}}</a>
                        <label for="rating">Rating:</label>
                        <p name="rating">{{review.rating}}</p>
                        <p><a href="{% url 'book_review:user' user_id=review.user.id %}">{{review.user.name}}</a> says: {{review.review}}</p>
                        <label for="date">Posted on:</label>
                        <p name="date">{{review.created_at}}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div id="scroll">
                {% if books %}
                    {% for book in books %}
                        <a href="{% url 'book_review:review_book' book_id=book.id %}">{{book.title}}</p>
                    {% endfor %}
                {% endif %}
            </div>
    </body>
</html>

apps/book_review/templates/book_review/user.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>User</title>
    </head>
    <body>
        <div class="header">
            <a href="{% url 'book_review:start' %}">Home</a>
            <a href="{% url 'book_review:add' %}">Add Book and Review</a>
            <a href="{% url 'login_registration:start' %}">Logout</a>
        </div>
        <div class="user">
            <label for="alias">User Alias:</label>
            <p name="alias">{{user.alias}}</p>
            <label for="name">Name:</label>
            <p name="name">{{user.name}}</p>
            <label for="email">Email:</label>
            <p name="email">{{user.email}}</p>
            <label for="count">Total Reviews</label>
            <p name="count">{{count}}</p>
        </div>
        <div class="reviewed_books">
            <h3>Posted Reviews on the following books</h3>
            {% if reviews %}
                {% for review in reviews %}
                    <a href="{% url 'book_review:review_book' book_id=review.book.id %}">{{review.book.title}}</a>
                {% endfor %}
            {% endif %}
        </div>
    </body>
</html>