apps/login_registration/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'login_registration'

urlpatterns = [
    url(r'^$', views.start, name='start'),
    url(r'^actions', views.submit, name='actions'),
]

main/urls.py
from django.conf.urls import url, include
#from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_registration.urls')),
    url(r'^book_review/', include('apps.book_review.urls')),
]

apps/login_registration/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$')

# Create your models here.

class UserManager(models.Manager):
    #Check name
    def nm_validate(self, name):
        if len(name) > 1:
            return True
        else:
            return False
    #Check alias
    def alias_validate(self, alias):
        if len(alias) > 1:
            return True
        else:
            return False
    #Check email length
    def email_validate(self, email):
        if not EMAIL_REGEX.match(email):
            return False
        else:
            return True
    #Check if email already exists
    def email_exists(self, email):
        check = User.objects.filter(email = email).exists()
        if check:
            return False
        else:
            return True
    #Check password
    def password_validate(self, password):
        if len(password) > 8:
            return True
        else:
            return False
    #Check password
    def password_match(self, password, confirm_password):
        if password == confirm_password:
            return True
        else:
            return False
    #Create User
    def createUser(self, name, alias, email, password):
        user = self.create(name = name, alias = alias, email = email, password = bcrypt.hashpw(password.encode(), bcrypt.gensalt()))
        return user
    #Check if passwords match
    def passwordsMatchCheck(self, entered_pw, db_pw):
        if bcrypt.hashpw(entered_pw.encode(), db_pw.encode()) != db_pw:
            return False
        else:
            return True

class User(models.Model):
    name = models.TextField(max_length = 50)
    alias = models.TextField(max_length = 50)
    email = models.EmailField(max_length = 100)
    password = models.CharField(max_length = 100)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    objects = UserManager()

apps/login_registration/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .models import User
import re

# Create your views here.
def start(request):
    return render(request, 'login_registration/index.html')

def submit(request):
    error = False
    if request.method == 'POST':
        if request.POST['action'] == 'register':
            name = User.objects.nm_validate(request.POST['name'])
            if not name:
                messages.add_message(request, messages.ERROR, 'Name too short!', extra_tags = 'name')
                error = True
            alias = User.objects.alias_validate(request.POST['alias'])
            if not alias:
                messages.add_message(request, messages.ERROR, 'Alias too short!', extra_tags = 'alias')
                error = True
            email = User.objects.email_validate(request.POST['email'])
            if not email:
                messages.add_message(request, messages.ERROR, 'Invalid email!', extra_tags = 'email')
                error = True
            email_exists = User.objects.email_exists(request.POST['email'])
            if not email_exists:
                messages.add_message(request, messages.ERROR, 'Email already exists!', extra_tags = 'email')
                error = True
            password = User.objects.password_validate(request.POST['password'])
            if not password:
                messages.add_message(request, messages.ERROR, 'Password too short!', extra_tags = 'password')
                error = True
            password_match = User.objects.password_match(request.POST['password'], request.POST['confirm_password'])
            if not password_match:
                messages.add_message(request, messages.ERROR, 'Passwords do not match!', extra_tags = 'match')
                error = True

            if error:
                print messages
                return redirect('login_registration:start')
            else:
                new = User.objects.createUser(name = request.POST['name'], alias = request.POST['alias'], email = request.POST['email'],password = request.POST['password'])
                context={
                    'user': new
                }
                request.session['user_id'] = new.id
                request.session['user_name'] = new.name
                return redirect('book_review:start')

        elif request.POST['action'] == 'login':
            try:
                user = User.objects.get(email = request.POST['email'])
            except Exception:
                messages.add_message(request, messages.ERROR, 'Email does not exist. Please register to login in!', extra_tags = 'deny')
                return redirect('login_registration:start')

            if not User.objects.passwordsMatchCheck(request.POST['password'], user.password):
                messages.add_message(request, messages.ERROR, 'Email or password is not correct!', extra_tags = 'deny')
                return redirect('login_registration:start')
            else:
                request.session['user_id'] = user.id
                request.session['user_name'] = user.name
                return redirect('book_review:start')

apps/login_registration/templates/login_registration/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Login</title>
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'login_registration/css/login_style.css' %}">
    </head>
    <body>
        <div class = "container center">
            <form class="new_user" action="{% url 'login_registration:actions' %}" method="post">
                {% csrf_token %}
                {% if messages %}
                    {% for message in messages %}
                        {% if 'name' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="text" name="name" placeholder="Name">
                {% if messages %}
                    {% for message in messages %}
                        {% if 'alias' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="text" name="alias" placeholder="Alias">
                {% if messages %}
                    {% for message in messages %}
                        {% if 'email' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="email" name="email" placeholder="Email">
                {% if messages %}
                    {% for message in messages %}
                        {% if 'password' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="text" name="password" placeholder="Password">
                {% if messages %}
                    {% for message in messages %}
                        {% if 'match' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="text" name="confirm_password" placeholder="Confirm Password">
                <button type="submit" name="action" value="register">Register</button>
            </form>
            <form class="login" action="{% url 'login_registration:actions' %}" method="post">
                {% csrf_token %}
                {% if messages %}
                    {% for message in messages %}
                        {% if 'deny' in message.tags %}
                            <p class = "red">{{message}}</p>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                <input type="email" name="email" placeholder="Email">
                <input type="text" name="password" placeholder="Password">
                <button type="submit" name="action" value="login">Login</button>
            </form>
        </div>
    </body>
</html>